### ISSUE TITLE
How to login

### ISSUE THREAD

**Issue by SekibOmazic** [SasPes/JavaSkop2017#1]
Hi there,

could you please help with project setup? I get all modules running but can't login into `http://localhost:8080/admin`. I do get redirected to OAuth server but since there is no default user in the MySQL so no chance to login. Adding a user directly into `user_account`didn't help either. Not sure what am I missing.

**Comment by SasPes** [comment]
Hi Sekib,

You need to set 3 things:

1. **user_account** (create account)
> REPLACE INTO `user_account` (`id`, `account_non_expired`, `account_non_locked`, `credentials_non_expired`, `enabled`, `password`, `username`) VALUES (1, b'1', b'1', b'1', b'1', 'admin', 'admin');

2. **user_authorities** (create authorities)
> REPLACE INTO `user_authorities` (`id`, `authority`) VALUES (1, 'ADMIN');

3. **user_account_authorities** (link account and authorities)
> REPLACE INTO `user_account_authorities` (`user_accounts_id`, `authorities_id`) VALUES (1, 1);

[JavaSkop2017 DB Export](https://github.com/SasPes/JavaSkop2017/files/1035019/javaskop2017.sql.txt)

**Comment by SekibOmazic** [comment]
Thanks. Closing this issue ...
